//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebScrapingUI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Home {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebScrapingUI.Resources.Home", typeof(Home).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one page must be selected.
        /// </summary>
        public static string Atleast {
            get {
                return ResourceManager.GetString("Atleast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Currency.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum price must be less than maximum price.
        /// </summary>
        public static string Less {
            get {
                return ResourceManager.GetString("Less", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Price.
        /// </summary>
        public static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Price.
        /// </summary>
        public static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency must be selected.
        /// </summary>
        public static string Must {
            get {
                return ResourceManager.GetString("Must", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of items.
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can choose only one category of pages.
        /// </summary>
        public static string Onecategory {
            get {
                return ResourceManager.GetString("Onecategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency and Prices.
        /// </summary>
        public static string Prices {
            get {
                return ResourceManager.GetString("Prices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your search.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nowadays, the role of online shops in people&apos;s lives is growing more and more. Suppose we want to search for some items from different online shops, we face trouble:.
        /// </summary>
        public static string WeScrapeText1 {
            get {
                return ResourceManager.GetString("WeScrapeText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to don&apos;t have to waste your time.
        /// </summary>
        public static string WeScrapeText10 {
            get {
                return ResourceManager.GetString("WeScrapeText10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to browsing each site..
        /// </summary>
        public static string WeScrapeText11 {
            get {
                return ResourceManager.GetString("WeScrapeText11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1) Fill in the same parameters and conduct search on each site separately.
        /// </summary>
        public static string WeScrapeText2 {
            get {
                return ResourceManager.GetString("WeScrapeText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2) Switch between multiple open tabs.
        /// </summary>
        public static string WeScrapeText3 {
            get {
                return ResourceManager.GetString("WeScrapeText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3) Waste your time browsing each site.
        /// </summary>
        public static string WeScrapeText4 {
            get {
                return ResourceManager.GetString("WeScrapeText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ScrapiWeb gives you the opportunity to conduct your.
        /// </summary>
        public static string WeScrapeText5 {
            get {
                return ResourceManager.GetString("WeScrapeText5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search on similar sites at the same time.
        /// </summary>
        public static string WeScrapeText6 {
            get {
                return ResourceManager.GetString("WeScrapeText6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and display all the possible.
        /// </summary>
        public static string WeScrapeText7 {
            get {
                return ResourceManager.GetString("WeScrapeText7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to results in one place.
        /// </summary>
        public static string WeScrapeText8 {
            get {
                return ResourceManager.GetString("WeScrapeText8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , and you.
        /// </summary>
        public static string WeScrapeText9 {
            get {
                return ResourceManager.GetString("WeScrapeText9", resourceCulture);
            }
        }
    }
}
